// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXPz9h_hVZuOQDXwuusSRQPJ-F_w98rqo',
    appId: '1:188701239795:android:bf659674ea9a7884c80a86',
    messagingSenderId: '188701239795',
    projectId: 'smartrecycle-a0d95',
    databaseURL: 'https://smartrecycle-a0d95-default-rtdb.firebaseio.com',
    storageBucket: 'smartrecycle-a0d95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjoX8hmhY2UIuyocd75egkrXbqZoBbW5g',
    appId: '1:188701239795:ios:61f54971a3d88794c80a86',
    messagingSenderId: '188701239795',
    projectId: 'smartrecycle-a0d95',
    databaseURL: 'https://smartrecycle-a0d95-default-rtdb.firebaseio.com',
    storageBucket: 'smartrecycle-a0d95.appspot.com',
    iosBundleId: 'com.example.smartrecycle',
  );
}
